source "https://rubygems.org"
gem "telegram-bot-ruby", "~> 1.0"
gem "require_all"
gem "solargraph"
gem "beaneater"
gem "discordrb"
gem "net-ping", "~> 1.7", ">= 1.7.8"
gem "jemalloc"
gem "spriggan", :git => "https://github.com/Ifiht/Spriggan", :branch => "main"
gem "redfairy", :git => "https://github.com/Ifiht/RedFairyBook", :branch => "main"
gem "listen", "~> 2.0"
gem "httpx"
gem "http"
gem "puma"
gem "rake"
gem "rufo"
gem "pp"
#gem 'rice' -- this is for torch-rb
#gem 'torch-rb' -- to be added later
