# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    shell: bash -leo pipefail {0}
    # doing this to make sure we read .bashrc
jobs:
  Build_Run_Ubuntu:

    runs-on: ubuntu-latest

    steps:
    #==[ Clone the repository ]==|
    - name: Checkout repository
      uses: actions/checkout@v3
    #==[ Setup environment ]=====|
    - name: Copy config.yml from example
      run: cp config.example.yml config.yml
    - name: Run init.sh
      run: ./init.sh
    #- name: Append to PATH
    #  run: echo "${HOME}/.rvm/bin" >> $GITHUB_PATH
    #==[ Run tests ]=============|
    - name: Test PM2
      run: bundle exec rake list_pm2
